### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by sohilpandya** [InFact-coop/building-exploratory#1]
We need to look into the following frameworks for the initial setup

- [x] Express
- [x] MongoDB
- [x] GraphQL
- [x] Google Sheet
- [x] React

**Comment by jessicasalmon** [comment]
* establish a server 
* create a MongoDB database 
* set up a google sheet with the data that has already been provided to us
* use tabletop.js to connect the server to the google sheet
* transfer the data from the google sheet to mongoose
