### ISSUE TITLE
Colour paletter

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/building-exploratory#11]
@NicoleCrockett and @KatieRussellTBE 

How would you like to proceed with the colour palette? is the current one ok or would you like to look into other two or so options? so you have any specific colours you would like me to try out on the layout?

**Comment by KatieRussellTBE** [comment]
Hi @nogainbar 
We're not convinced by the current colour palette, so it would be great if we could see the other options - would you be able to share a link with us to view them? Thanks

**Comment by nogainbar** [comment]
hey @KatieRussellTBE 

I am more than happy to send you a couple of other examples. Do you have a specific palette or a colour you are keen for me to try out? 

I think we shouldn't use more than two colours to keep it simple: a main colour and an accent one. 
In terms of accessibility, the main colour should be dark enough so that it can work both on the text and the graphical items like lines and illustrations. 

I would also say that in terms of the time I have on the these designs, I wont have enough time to do a deep research into branding and I know from experience that it is very easy to go into the colour rabbit hole.. 🕳🐇😌 

Unless you have something quite specific you would like me to use, if thats ok Ill send through two more options so that you can choose from those?

**Comment by KatieRussellTBE** [comment]
Hey @nogainbar 

Thanks for this - completely understand that time is limited and agree that the palette should be kept simple. Would it be possible for you to send us a link to all the other options that you had up on your screen during the meeting last week? We can then look over these and select two options for you. Thanks!

**Comment by KatieRussellTBE** [comment]
Also, I'm pulling together some photographs of different building types for the illustrated icons we talked about. I'll probably send them by email in a zip folder later today.

**Comment by nogainbar** [comment]
@KatieRussellTBE thats great thanx! 
I cant unfortunately share with you the colours that I chose because the website doesnt let me share that.. its kind of a really nice tool, still in BETA, that lets you choose your fav 50 colours and then composes a selection for you. 

would you like to give it a try yourself? http://khroma.co/ 
it might be interesting for you and also personalised to your taste!

If you hover over the cards, you can 'flip' those to see the colours flipped and if you click on the 'i' icon (info) you can see the colour's code. I need the HEX code of the two colours.

For accessibility (where is notes 'WCAG Ratio: AA or AAA') your selection should be:
AA Large (contrast above 3.0)
AA (contrast above 4.5)
AAA (contrast above 7.0)

**Comment by nogainbar** [comment]
Once you find two - three combinations, I am really happy to try those on the layout and send you an example of these would look applied.

**Comment by KatieRussellTBE** [comment]
@nogainbar - Great you've got the photos via WeTransfer!

I've tried the link that you sent through for the colour palette - I went through and chose 50 colours, but then when it tried to generate options, it didn't seem to get past this stage. It just kept generating and generating data with no results. I've tried again now, and it doesn't seem to want to even generate now... Do you have any suggestions? Perhaps you could please show us some alternatives? Thanks!

**Comment by nogainbar** [comment]
Hi @KatieRussellTBE, 

Here are a few selections of colours i saved from Khroma:

<img width="1268" alt="screen shot 2017-11-22 at 15 52 39" src="https://user-images.githubusercontent.com/12494147/33138469-7e25a772-cfa2-11e7-8b0a-cc8b8234c518.png">
<img width="1270" alt="screen shot 2017-11-22 at 15 52 54" src="https://user-images.githubusercontent.com/12494147/33138470-7e3df4da-cfa2-11e7-873d-03464b02973b.png">
<img width="1266" alt="screen shot 2017-11-22 at 15 53 02" src="https://user-images.githubusercontent.com/12494147/33138471-7e5a0986-cfa2-11e7-9c97-24b870e2ee51.png">
<img width="1259" alt="screen shot 2017-11-22 at 15 53 09" src="https://user-images.githubusercontent.com/12494147/33138472-7e7f218a-cfa2-11e7-9909-7ce831218c48.png">
<img width="646" alt="screen shot 2017-11-22 at 15 53 16" src="https://user-images.githubusercontent.com/12494147/33138473-7e9ace1c-cfa2-11e7-9b1b-c72aac002d0f.png">


Let me know if you like any of these?
The main colour would be the darker one (so the colour of the text and the separation lines)
