### ISSUE TITLE
Thoughts on photos

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/building-exploratory#12]
### Not google drive

So I've looked into this a bit more, and am slowly coming to the conclusion that google drive is *not* the best place for storing photos.

This is because:
- The URL structure is a bit unpredictable
- It's kind of impossible to get the actual url of a photo. The sharing link that google gives you does multiple redirects in order to get the actual photo. So I think this would create extra work in terms of implementing this logic. And then google might just go and deprecate that feature or change their logic anyway... so we need something more long term.
- I guess google drive wasn't really meant for this kind of thing, and it would be better to use google cloud services or something...

### Alternatives

- Alternatives include google cloud, dropbox or cloudinary. Cloudinary and dropbox provide free tier options. We used cloudinary for YiMovi and it comes with loads of free storage. Dropbox is probs a bit more 'familiar' though.
- Cloudinary has an SDK which provides lots of extra functionality like uploading from public URLs and transforming images. Not relevant for this sprint, but it could be useful in the future.
- It would also be an option if we were to offer our own upload functionality in the future (CMS-style). It's more user friendly (for devs) than something like S3.

There's loads of documentation. Here's a starting point: https://cloudinary.com/documentation/image_transformations

### Storing data

I think the best thing to do here would be to have a column in the spreadsheet for photos. URLs can be added in as a list of comma-separated photos, which we can convert to an array before adding to the DB.

### Possible google sheets use?

If using google sheets in the future, it's possible to upload a photo via a form. This photo goes to google drive. The links are also saved as a comma-separated links.
For now, I don't think we'd be able to use these photos directly on the website. They'd have to be copied to dropbox / cloudinary / other hosting platform manually. However, it's definitely possible to automate this process and we could do it as an extra feature if useful!

### General upload workflow

Anyone uploading photos needs to be aware of:
- file size: we need a strict limit (because of UX but also not exceeding quota on any hosting platform)
- dimensions: ask Noga what dimensions would be best... how flexible can we be?
At the moment, users will have to make sure that the photos are the right size themselves. There are lots of batch photo editing tools out there. Not sure what free options are available, but it's probably worth paying a few pounds for some kind of tool to reduce workflow here if we have several thousand photos. 
- Happy to help research options here, but please check what the POs want first :)

Please talk to the clients about the options and let me know if you need any more help!

relates #5

**Comment by jessicasalmon** [comment]
Thanks for this @emilyb7 - really helpful! 

We're using cloudinary. They can batch upload there, then they have to manually copy the url and put it in the correct column of google sheet. Then we manipulate the url in the code to format it (for size and quality) using [this feature of cloudinary](https://cloudinary.com/documentation/image_transformations#delivering_images_using_dynamic_urls). 

See the process in #20

**Comment by emilyb7** [comment]
sounds great 🎉
