### ISSUE TITLE
Volunteer Acknowledgement

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#17]
Hi @sohilpandya and @sohilpandya 

We'd like to include a thank you/acknowledgement to all the volunteers on the website. They need more than just a mention on the About tab/page - do you have any suggestions for how this could be delivered? Would it be a question of creating a Volunteer tab/page?

This is the website for another project we worked on, where people involved were credited: http://oureast20.london/index.php/about

Thanks!

**Comment by jessicasalmon** [comment]
After we all discussed this at the time we decided to credit the volunteers on the about page as originally planned, so closing this issue.
