### ISSUE TITLE
Building Entry Fields

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#18]
@nogainbar 

Please find below a list of the fields from the spreadsheet that we would like to appear for each listing entry:

Address with post code

Historic Significance (on spreadsheet at Statement of Significance, this should be at the top for users to see rather than the Description)

Date Built                        Building Type 

Conservation Area         Architectural Style

Date of Local Listing     Current Use

Description 

The layout of the fields above should reflect how they are displayed on the website.

Thank you!

**Comment by nogainbar** [comment]
@KatieRussellTBE this is the current layout according to the list above: https://invis.io/DSEIV3ZNJ#/264437917_Homepage_Single_list_view
Is that correct?

@sohilpandya @jessicasalmon , when chatting to Katie on the phone before she was asking about adding the name of the building next to the postcode so something like: 

EC1M 5NR, The Fox bup

@KatieRussellTBE have I understood this correctly and @sohilpandya and @jessicasalmon is that something we can do, does it entail adding another column?
I am not sure about the technicalities.
