### ISSUE TITLE
Fields that will be shown to the end user

### ISSUE THREAD

**Issue by sohilpandya** [InFact-coop/building-exploratory#2]
Hi Nicole & Katie,

Can you please provide us with a list of fields that will be used by the website to show to the end user. 
- name
- description
- location etc. 

It is important for us to know these as they will not be changeable once set.

**Comment by jessicasalmon** [comment]
@NicoleCrockett @KatieRussellTBE 

Have we come to a conclusion as to which fields we'll be requiring in the front end?

**Comment by KatieRussellTBE** [comment]
Hi Sohil and Jessica, 

Please find below a list of the fields we think will be required, but we would like to wait to finalise these until after the session on Friday:
Street Number
Street Name
Post Code
Ward 
Conservation Area
Date Built (actual)
Date Built (estimated/unconfirmed)
Architectural Style
Building Type
Current Use
Description of Building
Date of Local Listing
Statement of Significance
Recommendation

Hope that helps for now, and look forward to discussing things more on Friday.
