### ISSUE TITLE
Bugs on mobile 

### ISSUE THREAD

**Issue by jessicasalmon** [InFact-coop/building-exploratory#42]
- [x] Banner title should be smaller 
- [x] sometimes users have to click on map marker twice to see details view. Seems like it happens on the first marker a user clicks on, though not always 
- [ ] unable to render all of the map, after a user has scrolled down on the buildings list page (all markers do still load)
- [x] Alignment of footer icons 
- [x] Map on mobile is not in correct position

**Comment by jessicasalmon** [comment]
3. testing on android device: map height is initially 511px and then when you scroll it becomes 567px (full screen)

**Comment by jessicasalmon** [comment]
we think we may need to refresh the map on mobile when we click the 'mapswitch' icon

could either: 
- move function updateViewport to app component so it's accessible by map and mapswitch. Onclick call this function. 
- create a new function specifically for the mapSwitch in app

**Comment by sohilpandya** [comment]
Closing as the unchecked box is referred to in #50
