### ISSUE TITLE
A few things to do

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/building-exploratory#44]
Here are some things that you might already have in mind, but since I couldn't see an issue I didn't want them to get forgotten:

- [x] page title
- [ ] favicon
- [ ] possibly also manifest.json?
- [x] make sure cursor is always the hover cursor everywhere it should be, e.g. the building cards in the list

**Comment by sohilpandya** [comment]
Closing as most of it has been addressed. will be changing the favicon in the final PR.
