### ISSUE TITLE
Additional fields on the google sheet (photos + geolocation)

### ISSUE THREAD

**Issue by sohilpandya** [InFact-coop/building-exploratory#5]
@emilyb7 has asked us to look into photos and geolocation (lat,lon)

Both of these are vital for the app.

**Comment by sohilpandya** [comment]
Hey @emilyb7,

would it be possible to potentially help us think of a solution for photos, unsure as to where we would begin when thinking of uploading them and then using the url. 

Would love some thoughts on it. :)

**Comment by jessicasalmon** [comment]
Hey @emilyb7, it's sohil (from Jessica's Computer)

- what solution did you have in mind for the google form upload? we've done a little look around and google drive may/may not work... 😢

**Comment by emilyb7** [comment]
@sohilpandya can you explain what you mean by 'may not work'? What do you think the problem might be?

**Comment by sohilpandya** [comment]
@emilyb7 what did you have in mind? Exact steps? Upload to google drive and then use the url in the spreadsheet, asking them to manually add those?

**Comment by emilyb7** [comment]
@sohilpandya yes, i can explain in a little more detail later. Just wanted to check you haven't discovered any major problems?

**Comment by jessicasalmon** [comment]
closing as lat/long has been handled and we have Emily's thoughts on image uploading in #12
