### ISSUE TITLE
Footer: Make partner logos bigger 

### ISSUE THREAD

**Issue by jessicasalmon** [InFact-coop/building-exploratory#53]
## Description
View: Footer
Issue: partner logos are too small

## Screenshot
<img width="1430" alt="screen shot 2018-01-17 at 17 00 36" src="https://user-images.githubusercontent.com/19147734/35055819-f73bd4b6-fba7-11e7-9f4f-735d436fdbbd.png">

**Comment by KatieRussellTBE** [comment]
The partner logos are now better sized.
