### ISSUE TITLE
Footer: align partner icons to middle on mobile

### ISSUE THREAD

**Issue by jessicasalmon** [InFact-coop/building-exploratory#54]
## Description
View: Footer
Issue: partner logos are aligned to the left, should be in center 

## Screenshot
<img width="475" alt="screen shot 2018-01-17 at 17 03 05" src="https://user-images.githubusercontent.com/19147734/35055928-4df21126-fba8-11e7-95eb-bcea6aba6d2f.png">

**Comment by KatieRussellTBE** [comment]
The alignment is now fine.
