### ISSUE TITLE
Website not working on Internet Explorer

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#58]
Volunteer comment: the website only worked for me in firefox but not internet explorer. I tried clearing my cache, but it still didn't work.

**Comment by jessicasalmon** [comment]
It seems we have an issue with IE support for 'find'. We can use polyfill to support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

More info: 
https://stackoverflow.com/questions/37788536/object-doesnt-support-property-or-method-find-in-ie

**Comment by KatieRussellTBE** [comment]
Tested by a colleague and seems to now be working fine on Internet Explorer. - Thanks!
