### ISSUE TITLE
Home icon creates confusion as doesn't act as a 'back' button

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#59]
Home icon doesn't seem to function, and creates confusion as some users expect to press that to go back to first page, rather than have to click on 'Home'

Volunteer comments:
there doesn't seem to be a 'back' button - unusually the refresh button takes you back ?

**Comment by jessicasalmon** [comment]
<img width="497" alt="screen shot 2018-01-31 at 13 18 26 1" src="https://user-images.githubusercontent.com/19147734/35625183-4bfda86c-0689-11e8-8e06-8d10912112ad.png">

**Comment by KatieRussellTBE** [comment]
The home button now works as a 'back button' and while it doubles up sometimes with the 4boxes icon, it creates less confusion.
