### ISSUE TITLE
Possible building facade Illustrations by category

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/building-exploratory#6]
Hi @NicoleCrockett!

I know Sohil had mentioned in your meeting that I was thinking that if I have time, I would like to do a few nice illustration of the building facades for the website.
However, in order for me to to do that, Ill need a list of different building categories. Sohil and Jessica mentioned the 'Building type' category? (Commercial, Distillery building, Public House ect..)

This looks exciting and interesting but can only work depending on:
- how many categories there are. if there are too many, i am not sure ill have the time to do those all within this current scope. Would you be able to send me a finite list of this categories? also, would this list be finite?

- If you have good images of a building from each category that I could base my illustration on - It needs to be an image that represents that category, a sort of an 'archetype' of that category.

The other option I was thinking about is maybe going by 'Architectural Style' i.e - Georgian, Victorian ect.. If you like that, and/or think its more feasible, would you have images that you can send me that you would think represent those categories?

Happy to chat to you on the phone if you need more clarification about this.

**Comment by NicoleCrockett** [comment]
Hi Noga,
I shall ask Katie to go through the data and establish the number and type of categories and recommend a way forward. I'll also ask her to send through small paintings that one of our volunteers has done of the buildings she's been researching. They are lovely and it would be good to use them in the website in some way.
Can you tell me how to add a person to this conversation please? Katie knows the data best and could deal with these issues directly.
Many thanks,
Nicole

**Comment by nogainbar** [comment]
Hi @NicoleCrockett and @KatieRussellTBE, did you have a chance to look into these?
Ive tagged this issue with priority-1 as this would be of high priority for me start with the illustrations.
cheers!

**Comment by jessicasalmon** [comment]
Illustrations completed, closing issue
