### ISSUE TITLE
About button not obvious enough

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#63]
Some people seemed to miss this when viewing the website on a desk top - much more obvious on mobile device.

**Comment by jessicasalmon** [comment]
We've addressed this by underlining the 'About' button and increasing the text size on mobile

**Comment by KatieRussellTBE** [comment]
We've just had a look and the 'About' button doesn't appear to be bigger in size nor underlined when viewed on desktop computer and on Firefox.

**Comment by KatieRussellTBE** [comment]
Great, this now seems to be resolved.
