### ISSUE TITLE
Mobile Phone - Sizing of Address and Illustration Icon

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#64]
When viewing on Apple mobile phone, the size of the address and the illustration icon is disproportional.

**Comment by jessicasalmon** [comment]
We've fixed this issue. Attaching a couple of screenshots to show the difference between a shorter title and a longer title - the shorter title does look better/'cleaner', so it'd be good to get any duplicates cleaned up in the database. 

#### shorter title
<img width="376" alt="screen shot 2018-02-01 at 14 56 23" src="https://user-images.githubusercontent.com/19147734/35684903-29987df6-0760-11e8-924c-3627d13ea5a3.png">

#### longer title
<img width="377" alt="screen shot 2018-02-01 at 14 54 42" src="https://user-images.githubusercontent.com/19147734/35684901-297c7e76-0760-11e8-9917-b77a3f05017d.png">

**Comment by KatieRussellTBE** [comment]
This make sense - we're in the process of proofing and editing the database content we have so far.

**Comment by KatieRussellTBE** [comment]
For entries with long titles e.g. St. John’s Square Marking Setts....: the size of text in relation to illustrated icon is massive on mobile phone device. Is there a way of the text automatically reducing font size when goes above 6/8 words on a mobile device?

**Comment by jessicasalmon** [comment]
Hey @KatieRussellTBE - Just checked out the example that you gave and it's pretty massive for a title and I don't think the designs had a title this long in mind. It'd be preferable for the title to be approx three lines or less for a user to engage with the content. Could you edit title down if it's longer than three lines?

**Comment by KatieRussellTBE** [comment]
We can, and will, definitely edit down title as much as we can to reduce the likelihood of this happening. I just wondered if there was a way of automatically reduced font size on titles above a certain word count to ensure that it would stay proportional to the illustration.

**Comment by sohilpandya** [comment]
Hey! That is possible, but wasn't scoped in so would be in the additional work section, even if we were to scope this feature for the future, we would strongly recommend against having a long title.

Closing this issue as we've addressed the original issue. If you'd like us to look at the text sizing in the future, please feel free to open a new issue and assign it to the `backlog` milestone.
