### ISSUE TITLE
Returning to Map on Mobile Phone

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#65]
I think this may be because it's a two step process on a mobile device to get back to the map, but some volunteers couldn't figure this out.

Volunteer comments:
If you're using a phone and click on one of the buildings from the long list there doesn't appear to be a way to go back to the map and find out where the building is

**Comment by jessicasalmon** [comment]
Hey, this isn't a bug but the way that the app is intended to work on mobile. The idea being that with limited space on mobile a user can either find a building by list view or by the map view.
