### ISSUE TITLE
Clarity About 4 Boxes Icon 

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#67]
Volunteer Comments:

The icon to return to the full list is currently 4 boxes- could this be something a bit clearer or re-named to 'full list'

I thought the list button at the top of the photograph section should also have word by it saying "List"

**Comment by jessicasalmon** [comment]
We've played around with adding words to the list button but it breaks the design. We want to ensure that it is user friendly, but also try to keep the aesthetics so we've tried to solve the problem in another way:

*The home icon now takes you to the home page from anywhere on the site, so if a user is confused about the list button they can click on the home icon to get back to the same place. 

Please try it out and let us know your thoughts on this. Thanks!

**Comment by KatieRussellTBE** [comment]
I've just had a play and the Home icon still doesn't seem to work when you're on the About page, though it does seem to work when you're on a details page for an entry.

**Comment by KatieRussellTBE** [comment]
This is now clear, although there is overlap with the Home icon.
