### ISSUE TITLE
Difficulty Zooming Out on Map

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#69]
Volunteer Comments:

An easy zoom out is needed for the map (I could zoom in easily but not out. Is it me?)

**Comment by sohilpandya** [comment]
We'll add the zoom controls on the map which should make it easier to zoom in or out.

**Comment by KatieRussellTBE** [comment]
The added zoom control has helped make it easier to zoom in and out on the map.
