### ISSUE TITLE
Information from sheet to go on the specific page

### ISSUE THREAD

**Issue by nogainbar** [InFact-coop/building-exploratory#7]
Hi @NicoleCrockett!

Would you be able to list here all the information from the google sheet that you believe must be shown in the website?

**Comment by NicoleCrockett** [comment]
Hi Noga,
Can you please add Katie to all these conversations. Thanks.
I though she had sent through the list of fields we'd like to see included yesterday?
Best,Nicole

**Comment by nogainbar** [comment]
Hi @NicoleCrockett, yes Ive seen it now thank you! apologies for the duplication of question.
