### ISSUE TITLE
Visibilty of Scroll Bars on Laptop

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#72]
Volunteer Comments:

On a laptop there are no scroll bars not essential but people might expect them, no issues on phone very easy.

**Comment by jessicasalmon** [comment]
Scroll bars are doeable but would really break the design so we do not recommend it. We'd only suggest this is the feedback from majority of users is that it's hard to use, but scrolling when you can't see all of the content is quite a standard user behaviour these days.
