### ISSUE TITLE
Ensure Date Built Section Not Left Blank

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#73]
Volunteer Comments:

I think that under the Date Built section where a specific date is not known at least an estimated date should be given which it is not in some instances. 

Concerned to see that the Date field was blank in a number of cases

**Comment by jessicasalmon** [comment]
We'll address as laid out in #51.

**Comment by KatieRussellTBE** [comment]
This now seems to be fine. Where there are no dates, the text 'Unknown' appears.
