### ISSUE TITLE
Size of Images

### ISSUE THREAD

**Issue by KatieRussellTBE** [InFact-coop/building-exploratory#86]
The size of images seems to vary – some images don’t take up the full width of left column when viewed on a desktop device. Is this because the images are not yet standardised?

**Comment by jessicasalmon** [comment]
hey @KatieRussellTBE - these were just testing images but when we inject the real images they will all be the same size.

**Comment by KatieRussellTBE** [comment]
@jessicasalmon Great, thanks! I thought as much, but just wanted to confirm.
